Tags y SessionTags
platanus/fdbk1 pull request #1
Opened 2023-08-22 17:48 UTC by Ignaciomendezp

### Contexto

Pitch "Tag + Creación de Tags" de Trainee.​

### Qué se esta haciendo

* Creación de modelo Tag
* Creación de vista Tag en ActiveAdmin
* Creación de modelo SessionTag
* Creación de vista SessionTag en ActiveAdmin​

#### En particular hay que revisar
Que las vista de ActiveAdmin se hayan realizado correctamente y que la asociación entre modelos sea correcta.

-----------
#### Info Adicional (pantallazos, links, fuentes, etc.)

2023-08-22 18:51 UTC, difernandez requested changes
Algunos detalles chicos!

2023-08-22 18:51 UTC, difernandez commented on spec/models/tag_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
en los tests de modelos, siempre agregamos a lo menos un test que valida que la factory esté buena, échale un ojo en modelos existentes

2023-08-22 18:51 UTC, difernandez commented on db/migrate/20230821191140_create_tags.rb
> +      t.string :name
quizás podrías ponerle `null: false`, y una validación en el modelo, dado que en verdad no deberían haber tags sin nombres

2023-08-22 18:51 UTC, difernandez commented on spec/models/session_tag_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
idem el test de factory

2023-08-22 18:51 UTC, difernandez commented on spec/factories/session_tags.rb
> +    feedback_session { nil }
Estas asociaciones son requeridas, por defecto a nivel de modelo por el `belongs_to` y por el `null: false` a nivel de DB, por lo que esta factory está mala. Para asociarle un record válido, puedes sacar los `{ nil }` y dejar solo:
```ruby
    tag
    feedback_session
```

2023-08-22 18:52 UTC, difernandez commented
ah y otra cosa que olvidé decir! para el sandbox les estamos pidiendo que hagan dos review, una se hace automática a mi, lean o memo, y otra tendrían que hacerla ustedes con froggo

2023-08-22 19:10 UTC, Ignaciomendezp commented on db/migrate/20230821191140_create_tags.rb
> +      t.string :name
Perfecto! Creo que está la validación en el modelo de `Tag` como `validates :name, presence: true`. ¿Esto no es suficiente? De no serlo, tengo que modificar la migración y luego correrla de nuevo?

2023-08-22 19:10 UTC, Ignaciomendezp commented on spec/factories/session_tags.rb
> +    feedback_session { nil }
Perfecto, y basta con dejar la factory así o mejor que usemos `Faker`?

2023-08-22 19:40 UTC, difernandez commented on db/migrate/20230821191140_create_tags.rb
> +      t.string :name
uh si está la validación en el modelo, se me pasó porque estaba en un commit siguiente! (reviso por commits los PRs).
A nivel de modelo es suficiente eso, pero por lo general recomendamos agregar también a nivel de base de datos con el `null: false`, para lo que tendrías que hacer lo que dices: rollback, modificar migración, volver a correr, y aplicar los cambios con un rebase. Tener las dos es para más seguridad sobre la consistencia de los datos, no se podría bypassear la validación saltándose validaciones usando algo como `update_columns`, ya que eso se salta las validaciones a nivel de modelo, pero no DB

2023-08-23 14:04 UTC, FloValdes reviewed
lo veo bien! dejé unas cosas chicas

2023-08-23 14:04 UTC, FloValdes commented on app/admin/tags.rb
> +    f.semantic_errors
qué hace esta línea 😮 ?

2023-08-23 14:04 UTC, FloValdes commented on spec/factories/session_tags.rb
> +    feedback_session { nil }
normalmente en los proyectos lo dejamos así nomás, podría usarse el create(...) pero yo creo que no es necesario

2023-08-23 14:04 UTC, FloValdes commented on app/models/feedback_session.rb
> +  has_many :session_tags, dependent: :destroy
normalmente pondría en un mismo commit el agregar el `belongs_to` y el `has_many` porque al final es la misma relación por los dos lados

2023-08-23 14:04 UTC, FloValdes commented on app/models/tag.rb
> +  validates :name, presence: true
creo que esto lo hubiera puesto en el commit de crear la tag nomás, creo que se lee mejor cuando ves que se crea una tag con un nombre obligatorio por bdd y además tiene su validación que tener que acordarte 5 commits después que el nombre era obligatorio, no es para cambiarlo ahora igual

2023-08-23 14:04 UTC, FloValdes commented on spec/models/tag_spec.rb
hubiera hecho un rebase cambiando el commit en el que se creaba este test en vez de agregar un nuevo commit

2023-08-23 14:04 UTC, FloValdes commented on spec/models/session_tag_spec.rb
lo mismo con este commit y el rebase

2023-08-23 14:30 UTC, Ignaciomendezp commented on app/admin/tags.rb
> +    f.semantic_errors
Lo saqué del template que tienen sobre `ActiveAdmin` en el notion. Me parece que es para mostrar mensajes de error asociado a los campos. ¿Es mejor que lo quite?

2023-08-23 14:32 UTC, Ignaciomendezp commented on spec/factories/session_tags.rb
> +    feedback_session { nil }
Me pasa que me falla el `rspec` cuando no le pongo el `create(...)`. Será que tengo que cambiar el test para `SessionTag`?

2023-08-23 18:23 UTC, difernandez commented on spec/factories/session_tags.rb
> +    feedback_session { nil }
que es lo que te falla, que error tira? Y como lo tienes cuando falla?

2023-08-23 18:28 UTC, Ignaciomendezp commented on spec/factories/session_tags.rb
> +    feedback_session { nil }
Cuando lo tengo solo como:
```
    tag
    feedback_session
```
Me da esto en rspec:
![CleanShot 2023-08-23 at 14 27 07](https://github.com/platanus/fdbk1/assets/48481728/7cbeba36-08f0-4fa4-9603-ca7047910b15)

2023-08-23 19:42 UTC, FloValdes commented on spec/factories/session_tags.rb
> +    feedback_session { nil }
será por los validates de los ids? normalmente no hacemos esos validates porque el belongs_to te hace la validación igual

2023-08-23 19:43 UTC, FloValdes commented on app/admin/tags.rb
> +    f.semantic_errors
noo está perfect, es solo que nunca lo había visto jajaj @ldlsegovia te invoco para qué se usa?

2023-08-23 19:44 UTC, FloValdes approved these changes
💯

2023-08-23 19:51 UTC, ldlsegovia commented on app/admin/tags.rb
> +    f.semantic_errors
No estoy seguro pero creo que es para cuando agregás errores generales y no a atributos específicos. Si es un error de un atributo se muestra en el input pero si es general se muestra arriba

2023-08-23 19:51 UTC, FloValdes commented on app/admin/tags.rb
> +    f.semantic_errors
aah perfect, gracias!

2023-08-23 21:13 UTC, difernandez commented on app/models/session_tag.rb
> +  validates :feedback_session_id, presence: true
estas validaciones no son muy necesarias, el `belongs_to` por defecto valida la presencia de la asociación

2023-08-23 21:55 UTC, difernandez approved these changes
buena 🎉

2023-08-23 21:59 UTC, merged