Crear feedback session + tags
platanus/fdbk1 pull request #3
Opened 2023-08-30 15:16 UTC by Ignaciomendezp

### Contexto
Pitch de [tags + creación de sesiones](https://www.notion.so/platanus/Tags-Creaci-n-de-sesiones-83964f537b3d4d67ba1e02e0d0aff351) de proyecto Sandbox - Trainee.

### Qué se esta haciendo
* Se creó botón que desde la página de inicio dirige al formulario para crear sesión.
* Se creó formulario que permite crear sesiones de feedback correctamente.
* Se crearon "input tags". Para un correcto estilo de los tags (basado en el [Figma](https://www.figma.com/file/8qvUPFU10bXqVbhALa0aQc/Proyecto-Trainee---FDBK?node-id=304%3A3637&mode=dev)) se utilizó una función de hash que según el nombre del tag lo asocia a una clase en particular.
* Se modificó el componente de `feedback-session-item.vue` para que muestre sus respectivos tags.
* Se crearon tests para controladores correspondientes.
#### En particular hay que revisar
* Correcta implementación de componente `base-select.vue` y `back-button.vue`.
* Formulario de crear sesión de feedback (`feedback-sessions-new.vue`).
* Controlador de sesión de feedback.
* Job para crear sesión de feedback (`create_feedback_session_job.rb`).
* Tests correspondientes.
-----------
#### Info Adicional (pantallazos, links, fuentes, etc.)

Se utilizó [esta librería](https://github.com/sipec/vue-tags-input) para el manejo de tags. No existe declaración de tipos para `typescript` de esta librería (o al menos no encontré) por lo que agregué un archivo `vue3-tags-input.d.ts` que acepta cualquier tipo.

Vistas basadas en este [Figma](https://www.figma.com/file/8qvUPFU10bXqVbhALa0aQc/Proyecto-Trainee---FDBK?node-id=304%3A3637&mode=dev).

2023-08-30 15:18 UTC, monkeyci commented on app/jobs/create_feedback_session_job.rb
> +      session_tag = SessionTag.create(
⚠️ **[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Lint/UselessAssignment: Useless assignment to variable - session_tag.

2023-08-30 15:18 UTC, monkeyci commented on spec/jobs/create_feedback_session_job_spec.rb
> +    let(:feedback_session_date) { Time.now.strftime("%Y-%m-%d") }
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Rails/TimeZone: Do not use Time.now without zone. Use one of Time.zone.now, Time.current, Time.now.in_time_zone, Time.now.utc, Time.now.getlocal, Time.now.xmlschema, Time.now.iso8601, Time.now.jisx0301, Time.now.rfc3339, Time.now.httpdate, Time.now.to_i, Time.now.to_f instead.

2023-08-30 15:18 UTC, monkeyci commented on spec/jobs/create_feedback_session_job_spec.rb
> +    it "creates a feedback session and associates tags" do
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/ExampleLength: Example has too many lines. [17/10]

2023-08-30 15:18 UTC, monkeyci commented on spec/jobs/create_feedback_session_job_spec.rb
> +      expect {
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Style/BlockDelimiters: Avoid using {...} for multi-line blocks.

2023-08-30 15:18 UTC, monkeyci commented on spec/jobs/create_feedback_session_job_spec.rb
> +        CreateFeedbackSessionJob.new.perform(
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/DescribedClass: Use described_class instead of CreateFeedbackSessionJob.

2023-08-30 15:18 UTC, monkeyci commented on spec/jobs/create_feedback_session_job_spec.rb
> +      }.to change(FeedbackSession, :count).by(1)
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/ExpectChange: Prefer change { FeedbackSession.count }.

2023-08-30 15:18 UTC, monkeyci commented on spec/jobs/create_feedback_session_job_spec.rb
> +        .and change(SessionTag, :count).by(tag_names.length)
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/MultilineMethodCallIndentation: Align .and with .by on line 18.

2023-08-30 15:18 UTC, monkeyci commented on spec/jobs/create_feedback_session_job_spec.rb
> +        .and change(SessionTag, :count).by(tag_names.length)
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/ExpectChange: Prefer change { SessionTag.count }.

2023-08-30 15:18 UTC, monkeyci commented on spec/requests/api/internal/feedback_sessions_spec.rb
> +  describe 'POST /create' do
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/MultipleMemoizedHelpers: Example group has too many memoized helpers [6/5]

2023-08-30 15:18 UTC, monkeyci commented on spec/requests/api/internal/feedback_sessions_spec.rb
> +    let!(:feedback_session_date) { Time.now.strftime("%Y-%m-%d") }
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Rails/TimeZone: Do not use Time.now without zone. Use one of Time.zone.now, Time.current, Time.now.in_time_zone, Time.now.utc, Time.now.getlocal, Time.now.xmlschema, Time.now.iso8601, Time.now.jisx0301, Time.now.rfc3339, Time.now.httpdate, Time.now.to_i, Time.now.to_f instead.

2023-08-30 15:18 UTC, monkeyci commented on spec/requests/api/internal/feedback_sessions_spec.rb
> +    context 'with authorized user' do
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/MultipleMemoizedHelpers: Example group has too many memoized helpers [6/5]

2023-08-30 15:18 UTC, monkeyci commented on spec/requests/api/internal/feedback_sessions_spec.rb
> +        expect { perform }.to change(FeedbackSession, :count).by(1)
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/ExpectChange: Prefer change { FeedbackSession.count }.

2023-08-30 15:18 UTC, monkeyci commented on spec/requests/api/internal/feedback_sessions_spec.rb
> +    context 'with unauthenticated user' do
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/MultipleMemoizedHelpers: Example group has too many memoized helpers [6/5]

2023-08-30 15:18 UTC, monkeyci commented on spec/requests/api/internal/feedback_sessions_spec.rb
> +        expect { perform }.not_to change(FeedbackSession, :count)
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/ExpectChange: Prefer change { FeedbackSession.count }.

2023-08-30 19:01 UTC, nicolasguridi commented on app/javascript/components/base-button.vue
> +    tag?: string
esta prop `tag` no se usa o sí?

2023-08-30 19:01 UTC, nicolasguridi commented on app/assets/images/icons/arrow-back.svg
> +<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000"><path d="M0 0h24v24H0z" fill="none"/><path d="M20 11H7.83l5.59-5.59L12 4l-8 8 8 8 1.41-1.41L7.83
creo que una buena práctica es ponerle `currentColor` al fill, para que tome el color que tiene el texto donde sea que uses el ícono. Así en algunos casos te ahorras tener que poner el `fill-color-x` en el estilo del ícono

2023-08-30 19:01 UTC, nicolasguridi commented on app/javascript/components/feedback-sessions-new.vue
> +import BaseButton from './base-button.vue';
si los definiste como componentes globales en el `application.ts`, entonces no es necesario importarlos. Si no los definiste como componentes globales, te recomiendo hacerlo porque se usan en varias partes

2023-08-30 19:01 UTC, nicolasguridi commented on app/javascript/components/base-select.vue
> +);
cacha que si la prop es opcional, no es necesario definir que su valor por defecto es undefined. No está mal definirlo, pero si quieres ahorrar código y trabajo puede ser una buena opción

2023-08-30 19:01 UTC, nicolasguridi commented on app/javascript/components/base-select.vue
> +  <div>
mientras menos nesteado el html, mejor. Así que evitaría poner este div a menos que sea necesario

2023-08-30 19:01 UTC, nicolasguridi commented on app/javascript/components/feedback-sessions-new.vue
> +import api from 'api/feedback-sessions';
te recomiendo darle un nombre más descriptivo a esta api (feedbackSessionsApi, por ejemplo). Sobre todo si además estás importando otra api en el mismo archivo

2023-08-30 19:01 UTC, nicolasguridi commented on app/javascript/components/feedback-sessions-new.vue
> +const feedbackSessionDate = ref<string>('');
creo que sería más correcto que estas variables partieran siendo `undefined`, dado que realmente no están definidas

2023-08-30 19:01 UTC, nicolasguridi commented on app/javascript/components/feedback-sessions-new.vue
> +const providerUserId = ref<number>(0);
lo mismo para este caso, si no está definido mejor un `undefined` que un `0`

2023-08-30 19:01 UTC, nicolasguridi commented on app/javascript/components/feedback-sessions-new.vue
> +  }
esto es una sugerencia muy picky jajaja no está mal como lo hiciste pero hay otra manera que puede ser mejor:
```typescript
function addTag() {
  if (newTagName.value === '' && tagNames.value.includes(newTagName.value)) return;

  tagNames.value.push(newTagName.value);
  newTagName.value = '';
}
```

2023-08-30 19:01 UTC, nicolasguridi commented on app/javascript/components/feedback-sessions-new.vue
> +onMounted(fetchUsers);
por qué no pasar los users como una prop a la vista? así el usuario no tiene que esperar a que se monte el componente para que se vayan a buscar a los usuarios

[aquí](https://www.notion.so/platanus/Gu-a-de-Estilo-67506d25082349d9b4128f25f1f81a69?pvs=4#2ae9dec29904413cbfa3d572e4db5170) la recomendación en la guía de estilo

2023-08-30 19:01 UTC, nicolasguridi commented on app/javascript/components/feedback-sessions-new.vue
> +        v-model="providerUserId"
te recomiendo leer [esto](https://vuejs.org/guide/components/v-model.html) para usar `v-model` en componentes custom. El problema que me parece que tiene este componente es que no hay una prop para el `modelValue`, entonces si `providedUserId` tuviera un valor inicial, o se cambiara desde otro lado, ese valor no se reflejaría en el componente. Probablemente en este caso no sea nada terrible, pero es bueno aprenderlo

2023-08-30 19:01 UTC, nicolasguridi commented on app/jobs/create_feedback_session_job.rb
> +    feedback_session = FeedbackSession.create(
te recomiendo usar `create!` así si falla la creación se levantará una excepción que interrumpirá la ejecución del job. Así evitas tener que llamar `feedback.save` más adelante

2023-08-30 19:01 UTC, nicolasguridi commented on app/jobs/create_feedback_session_job.rb
> +      session_tag = SessionTag.create(
lo mismo que antes, usaría la versión con `!` de `find_or_create_by` y de `create` para que se levante una excepción en caso de cualquier problema

2023-08-30 19:01 UTC, nicolasguridi commented on @types/@sipec/vue3-tags-input.d.ts
> +  export default anyContent;
qué pasa si no pones estas líneas?

2023-08-30 19:01 UTC, nicolasguridi commented on app/javascript/components/feedback-sessions-new.vue
> +  return trimmedInput.charAt(0).toUpperCase() + trimmedInput.slice(1).toLowerCase();
esto es una función que perfectamente podría ir en una util, porque es algo muy general que podrías usar en otro lugar (incluso en otra app)

2023-08-30 19:01 UTC, nicolasguridi commented on app/javascript/components/feedback-sessions-new.vue
> +  }
para el manejo de llamadas a la api te recomiendo usar tanstack-query, en especial sus [mutations](https://tanstack.com/query/v4/docs/vue/guides/mutations). Te ahorra harto boilerplate (como el createdStatus == 201 y cosas así)

2023-08-30 19:01 UTC, nicolasguridi commented on app/javascript/utils/tag-class.ts
> +}
de repente si hay una librería que hace esta misma pega puede ser mejor usar eso, para no tener que escribir y mantener este código

2023-08-30 19:06 UTC, nicolasguridi commented on spec/jobs/create_feedback_session_job_spec.rb
> +        )
te recomiendo que antes del `it` definas un método perform para no tener que hacer esta llamada en cada test. Algo así:
```ruby
def perform
  described_class.perform(
          provider_user,
          receiver_user,
          feedback_session_date,
          tag_names
        )
end
``` 
Luego en el test haces 
```ruby
it "creates a feedback session" do
  expect { perform }.to change { FeedbackSession.count }.by(1)
end
```

2023-08-30 19:08 UTC, nicolasguridi commented on spec/jobs/create_feedback_session_job_spec.rb
> +      expect_correct_tags_associated(feedback_session, tag_names)
creo que esto se podría simplificar a algo como:
```ruby
expect { FeedbackSession.last.tags.pluck(:name) }.to match_array(tag_names)
``` 
así queda harto más fácil de entender, te ahorras consultas a la base de datos, etc.

2023-08-30 19:09 UTC, nicolasguridi commented on spec/requests/api/internal/feedback_sessions_spec.rb
> +  describe 'POST /create' do
este warning es cero terrible, en mis proyectos tiendo a desactivar la regla nomás. Igual trata de no tener miles de `let` jajaja

2023-08-30 19:15 UTC, nicolasguridi commented
@Ignaciomendezp te dejé varios comentarios, ideal si los resuelves/contestas todos. Cualquier duda me preguntas nomás.

Encuentro que el PR está bueno, dejé harto comentario pero me parece que hiciste una buena pega 👏 👏  

Una sugerencia final: trata de que en tus PR las modificaciones a un mismo archivo queden en el mismo commit. Así le facilitas la pega al revisor, que muchas veces va commit por commit revisando los cambios (como lo hice ahora, por eso hay comentarios de cosas que finalmente no quedaron en la última versión jaja). Si quieres una explicación más detallada dime nomás

2023-08-31 13:28 UTC, Ignaciomendezp commented on app/javascript/components/base-button.vue
> +    tag?: string
Tienes razón!

2023-08-31 14:01 UTC, Ignaciomendezp commented on app/javascript/components/base-select.vue
> +);
El eslint me alega si no le pongo un valor por defecto 🤔 ¿Será que lo estoy haciendo mal? Todavía me pierdo un poco con las restricciones que tiene typescript. Intenté algo así:

```
const props = withDefaults(
  defineProps<{
    options?: { id: number; name: string }[]
  }>(), {});
```

2023-08-31 14:06 UTC, nicolasguridi commented on app/javascript/components/base-select.vue
> +);
si le sacas el `withDefaults` debería dejar de alegar y funcionar igual de bien

2023-08-31 14:12 UTC, Ignaciomendezp commented on @types/@sipec/vue3-tags-input.d.ts
> +  export default anyContent;
Nada 😅

2023-08-31 19:15 UTC, difernandez requested changes
buena! dejé algunos detashes

2023-08-31 19:15 UTC, difernandez commented on app/views/app/feedback_sessions/new.html.erb
> +<feedback-sessions-new />
~En archivos `.erb` no se puede usar self closing tags, esto debería ser `<feedback-sessions-new></feedback-sessions-new>`~. EDIT: esto cambió en otro commit

2023-08-31 19:15 UTC, difernandez commented on app/javascript/components/feedback-sessions-new.vue
> +</template>
Agregando a lo que dijo nico, trataría de evitar commitear cosas como esta que son un archivo con algo placeholder/no real que se va a reemplazar en un commit futuro

2023-08-31 19:15 UTC, difernandez commented on app/jobs/create_feedback_session_job.rb
> +    end
Propongo una alternativa: que este método sea un setter en el modelo, tipo `def tag_names=`. Con esto podrías hacer solo `FeedbackSession.create!(..., tag_names: tag_names)`, incluso directo en el controller, sin necesitar el job. Así la lógica de creación también queda en el modelo. Si se hace esto, el setter debería funcionar para create y update si, para que sea consistente. Con algo como `self.tags = tag_names.map {...}` debería funcar, creeo.
Se entiende? Qué opinas?

2023-08-31 19:15 UTC, difernandez commented on app/javascript/utils/tag-class.ts
> +}
Este código está medio difícil de entender. Tratamos de poner harto énfasis en que las cosas sean fáciles de entender, tanto lo que se hace, el cómo y el por qué: así es más fácil de mantener tambn. Lo que lo hace medio críptico son varios puntos:
- Uso de operadores poco comunes como el bitwise y el left shift
- Nombre del método quizás
- Creo que no queda clara la razón del método. Entiendo que es como para obtener un número fijo a partir del string de un tag, no? No se si esto es un algoritmo particular de algo, pero por qué no usar algo más simple como `name.length % tagClasses.length` por ejemplo? O algo un pelín más complejo que eso, pero igual más simple como sumar los charCodes?

2023-08-31 19:15 UTC, difernandez commented on app/controllers/api/internal/feedback_sessions_controller.rb
> +  end
ideal que el create retorne el objeto creado, y por lo que veo el job no lo hace

2023-08-31 19:15 UTC, difernandez commented on app/controllers/api/internal/feedback_sessions_controller.rb
> +    provider_user = User.find(params[:provider_user_id])
no es 100% necesario buscar el usuario, puedes pasarle el id directo al create, y así te ahorras una llamada a la db

2023-08-31 19:15 UTC, difernandez commented on app/javascript/components/base-select.vue
> +  <div>
para agregar, creo que el de abajo también es medio innecesario, o no? Podría ser el select directo no más

2023-08-31 19:15 UTC, difernandez commented on app/javascript/components/feedback-sessions-new.vue
> +      />
puede ser en otro PR, pero sería bacán que salgan como opciones del select para autocomplete los tags ya existentes

2023-08-31 19:15 UTC, difernandez commented on app/javascript/utils/tag-class.ts
> +    'orange-tag',
creo que pondría directamente acá las clases de tailwind, onda `bg-orange-50 border-orange-500 text-orange-500`, así evitas clases nuevas y se acorta el `<style>` del componente

2023-09-04 18:05 UTC, Ignaciomendezp commented on app/javascript/components/feedback-sessions-new.vue
> +const feedbackSessionDate = ref<string>('');
![CleanShot 2023-08-31 at 11 52 14](https://github.com/platanus/fdbk1/assets/48481728/60f3d134-07c1-4923-b7a2-49bc4273c7aa)

Si los pongo inicialmente como `undefined` tengo problemas al llamar a la api, ¿Cuál es la mejor manera de manejar esto? No encontré cómo hacerlo con `TanStack Query`

Algo así hice y no me salen errores, pero no estoy seguro si estoy manejando de manera correcta el caso de parámetros no válidos:
```
const { mutate: createFeedbackSession } = useMutation({
  mutationFn: () => {
    if (
      providerUserId.value !== undefined &&
      feedbackSessionDate.value !== undefined &&
      currentTagNames.value.length > 0
    ) {
      return feedbackSessionsApi.create(providerUserId.value,
        feedbackSessionDate.value,
        currentTagNames.value.map(obj => obj.text),
      );
    }

    return Promise.reject();
  },
  onSuccess: () => {
    window.location.href = '/';
  },
});
```
@nicolasguridi

2023-09-04 18:05 UTC, Ignaciomendezp commented on app/javascript/components/feedback-sessions-new.vue
> +        v-model="providerUserId"
Entonces bastaría con agregar `modelValue` como `prop` al componente de `base-select.vue`? Me parece lo de emitir la actualización de la variable está.

2023-09-04 18:05 UTC, Ignaciomendezp commented on app/jobs/create_feedback_session_job.rb
> +    end
Me parece super! Queda mas limpio

2023-09-04 18:05 UTC, Ignaciomendezp commented on app/controllers/api/internal/feedback_sessions_controller.rb
> +    provider_user = User.find(params[:provider_user_id])
~~Me da `AxiosError 500` si llamo al Job con el `provider_user_id`, quizás no lo estoy creando de la manera correcta?
Esto tengo en el `create_feedback_session_job.rb`:~~
```
FeedbackSession.create(
   provider: provider_user,
   receiver: receiver_user,
   session_date: feedback_session_date,
   tag_names: tag_names
)
```

EDIT: Solucionado!

2023-09-04 18:05 UTC, Ignaciomendezp commented on app/javascript/utils/tag-class.ts
> +    'orange-tag',
Me pasa que si especifico las clases de la manera que me dices, entonces las clases que vienen por defecto en la librería `VueInputTags` las sobreescriben.
Pero si las especifico de la manera que las tengo en `feedback-sessions-new.vue`:
```
.ti-valid.orange-tag.ti-tag {
   ...
}
```
Como especifico el estilo de un elemento que contiene 3 clases, como es más específico entonces este estilo "manda" y puede sobreescribir las clases que tiene `VueInputTags`.
Intenté de ver algún equivalente a `!important` de CSS en tailwind, pero al parecer no existe. 🤔

2023-09-04 18:23 UTC, nicolasguridi commented on app/javascript/components/feedback-sessions-new.vue
> +        v-model="providerUserId"
sí! tal cual. Y hacer que el select dentro de `base-select` muestre a `modelValue` si es que está definido

2023-09-04 18:44 UTC, nicolasguridi commented on app/javascript/components/feedback-sessions-new.vue
> +const feedbackSessionDate = ref<string>('');
lo veo bien, quizás podrías definir la mutationFn fuera de `useMutation` para que quede más fácil de leer eso sí

2023-09-04 19:06 UTC, monkeyci commented on app/javascript/components/feedback-sessions-new.vue
> +  const res = await usersApi.index();
🚫 **[tsc]** <2339> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Property 'index' does not exist on type '{ login(email: string, password: string, remember: boolean): Promise<AxiosResponse<any, any>>; register(user: UserForm): Promise<AxiosResponse<any, any>>; }'.

2023-09-04 22:02 UTC, nicolasguridi approved these changes
te dejé unos comentarios chicos, pero bien en general 💯

2023-09-04 22:02 UTC, nicolasguridi commented on app/javascript/utils/capitalize-string.ts
> +  return trimmedInput.charAt(0).toUpperCase() + trimmedInput.slice(1).toLowerCase();
no sería mejor hacer el trim antes de revisar si el largo es cero? me imagino que `input` podría ser `'   '` y en ese caso no se cumpliría la condición del `if`, luego al hacer trim obtendrías `''` y no tiene mucho sentido ejecutar la última línea sobre ese string. No tira error igual, pero creo que hace más sentido trimmear antes de revisar el largo

2023-09-04 22:02 UTC, nicolasguridi commented on app/jobs/create_feedback_session_job.rb
para qué es este job? por qué no llamar directamente a `FeedbackSession.create(...`?

2023-09-04 22:02 UTC, nicolasguridi commented on tsconfig.json
> +    "@types/**/*.d.ts"
😮 por qué tuviste que agregar esto? la carpeta con los `.d.ts` no está dentro de `app/javascript`?

2023-09-05 12:07 UTC, Ignaciomendezp commented on tsconfig.json
> +    "@types/**/*.d.ts"
Por lo que entendí la carpeta con los `.d.ts` van en la carpeta raíz 🤨 pero puedo estar equivocado 👀

2023-09-05 12:14 UTC, nicolasguridi commented on tsconfig.json
> +    "@types/**/*.d.ts"
quizás en proyectos que sean solo frontend se haga así, pero acá como en la misma aplicación hay frontend y backend tendemos a poner todo lo que es javascript/typescript en `app/javascript`. Creo que tiene más sentido, por si algún día se decide separar el front y el back, así sería llegar y llevarse la carpeta

2023-09-05 12:38 UTC, difernandez commented on app/javascript/utils/tag-class.ts
> +    'orange-tag',
ahhh yaya es por especificidad de css, dejalo como está entonces no más!

2023-09-05 12:46 UTC, nicolasguridi approved these changes
te dejé dos comentarios chicos de cosas que no había visto antes. Igual son detalles, así que dejo el approve 👍

2023-09-05 12:46 UTC, nicolasguridi commented on app/controllers/app/feedback_sessions_controller.rb
>      @feedback_session = FeedbackSession.new
es necesario definir `@feedback_session` en esta acción del controlador? si usas `.new` ni siquiera se guarda en la base de datos, entonces me parece que podrías borrarlo y no pasaría nada

2023-09-05 12:46 UTC, nicolasguridi commented on app/controllers/api/internal/feedback_sessions_controller.rb
> +    respond_with FeedbackSession.create(
detalle chico: si usas `create!` en vez de `create` te va a levantar una excepción en caso de que falle la creación del record. Y eso normalmente es mejor a que falle silenciosamente y no te enteres

2023-09-05 13:09 UTC, difernandez approved these changes
👌 👌

2023-09-05 13:33 UTC, merged