Agregar tags a vistas de sesiones de feedback
platanus/fdbk1 pull request #3
Opened 2023-01-03 18:40 UTC by riadeane

### Contexto
Uno de los proyectos de sandbox de los trainees es trabajar en una [aplicación de feedback técnico](https://www.notion.so/platanus/Aplicaci-n-de-feedback-t-cnico-6fbf380eec134f0292bd1c0ebd224af8). Dentro de este proyecto a mí me corresponde realizar el pitch [Tags + Creación de sesiones de feedback](https://www.notion.so/platanus/Tags-Creaci-n-de-sesiones-83964f537b3d4d67ba1e02e0d0aff351).
​
### Qué se esta haciendo
Aquí hice un componente para todos los tags, que se llama base-tag. Este componente luego pasa a ser parte de la página de index (mediante feedback-session-item) y en el formulario de creación de sesiones de feedback (mediante tag-select). Una vez que ya está todo listo en el frontend, se agregan los tags al create endpoint de la API para las sesiones de feedback, para que estén asociados en el backend.
​
#### En particular hay que revisar
En general el tema de la separación de responsabilidades en cada componente y en el endpoint de la API. Abstraer la asignación de colores a un composable creo que ayudó en ese tema, pero creo que es lo que me tenía más preocupada.
​

-----------
#### Info Adicional (pantallazos, links, fuentes, etc.)

[tags_fdbk_sessions.webm](https://user-images.githubusercontent.com/62292336/210420542-0d3b0ed2-e8fd-4a82-81d8-4240bcbd8381.webm)

2023-01-03 19:07 UTC, ldlsegovia requested changes
Algunas cositas pero está excelente la verdad 👏🏻

2023-01-03 19:07 UTC, ldlsegovia commented on app/controllers/api/internal/feedback_sessions_controller.rb
> +    feedback_session = FeedbackSession.create!(
Pondría todo en una transacción. Algo asÍ:

```ruby
ActiveRecord::Base.transaction do
    feedback_session = FeedbackSession.create!(
      provider_id: feedback_session_params[:provider_id],
      session_date: feedback_session_params[:session_date],
      receiver: current_user
    )

    feedback_session.tags << feedback_session_params[:tags_ids].map { |tag_id| Tag.find(tag_id) }
end
```

para que si falla la asociación con tags, no te quede un objeto inconsistente. Mejor que o pase todo o falle todo.

2023-01-03 19:07 UTC, ldlsegovia commented on app/controllers/api/internal/feedback_sessions_controller.rb
> +    feedback_session.tags << feedback_session_params[:tags_ids].map { |tag_id| Tag.find(tag_id) }
no es obligatorio parar tags, no? En este caso, revisa entonces si viene `feedback_session_params[:tags_ids]`. Entiendo que desde la vista siempre mandás el atributo pero a la API tenés que pensarla de forma desconectada a la vista

2023-01-03 19:07 UTC, ldlsegovia commented on app/controllers/app/feedback_sessions_controller.rb
> +    @tags = Tag.all
Veo en el serializer que solo usar id y name. Es buena idea entonces hacer `Tag.all.select(:id, :name)`. Es un detalle pero cualquier data extra que necesites serializar toma tiempo

2023-01-03 19:07 UTC, ldlsegovia commented on app/controllers/app/feedback_sessions_controller.rb
> +    @tags = Tag.all
lo mismo acá

2023-01-03 19:07 UTC, ldlsegovia commented on lib/fake_data_loader.rb
> +    tags = %w[Backend Frontend UX/UI Vue Rails Tailwind TypeScript ActiveAdmin RSpec CircleCI Modelos]
Cool que hayas agregado data de prueba!

2023-01-03 19:57 UTC, riadeane commented on app/controllers/app/feedback_sessions_controller.rb
> +    @tags = Tag.all
Buena idea!! Lo cambio

2023-01-03 19:58 UTC, riadeane commented on app/controllers/api/internal/feedback_sessions_controller.rb
> +    feedback_session.tags << feedback_session_params[:tags_ids].map { |tag_id| Tag.find(tag_id) }
Se me ocurre hacerlo así:
```ruby
if feedback_session_params[:tags_ids].present?
  feedback_session.tags << feedback_session_params[:tags_ids].map { |id| Tag.find(id) }
end
```

2023-01-03 19:59 UTC, riadeane commented on app/controllers/api/internal/feedback_sessions_controller.rb
> +    feedback_session = FeedbackSession.create!(
Sii, buena idea :D voy con ese cambio

2023-01-03 20:23 UTC, flouMicaza reviewed
Está super pro!! Lo único que no me quedó claro es lo del composable, como que no entendí lo que hace, entonces tampoco entiendo porqué se le pasan todos los tags a las props en el item del feedback session. 

Aparte de eso dejé sugerencias más bien estéticas para hacer las cosas "a la Platanus" todo discutible obvia. Cuéntame qué opinas 😄

2023-01-03 20:23 UTC, flouMicaza commented on app/javascript/components/base-tag.vue
> +      :src="require('images/icons/cross.svg')"
Para otra vez, yo agregaría el svg de la cruz en este mismo commit, ya que aquí es donde se agrega. Siento que no suma mucho que vaya en su proprio commit.

2023-01-03 20:23 UTC, flouMicaza commented on app/javascript/composables/giveTagsColor.ts
> +export default function giveTagsColor(tags : Tag[]) {
no caché lo que have giveTagsColor 🤔

2023-01-03 20:23 UTC, flouMicaza commented on app/javascript/components/feedback-sessions-item.vue
> +  tags: Tag[],
No caché bien porqué se le pasan todos los tags en las props.

2023-01-03 20:23 UTC, flouMicaza commented on spec/requests/api/internal/feedback_sessions_spec.rb
> +      it { expect(created_session['tags'].count).to eq(1) }
Aquí agregaría un test para el caso en que no se hayan seleccionado tags, por lo mismo que decía leandro.

2023-01-03 20:23 UTC, flouMicaza commented on spec/requests/api/internal/feedback_sessions_spec.rb
> +      it { expect(created_session['tags'].count).to eq(1) }
Agregaría un context que fuera algo como 
```
  context 'without tags' do
    let(:params) { { provider_id: provider.id, session_date: '2023-01-01', tags_ids: [] } }
    it { expect(created_session.tags.count).to eq(0)
  end 
```

2023-01-03 20:42 UTC, riadeane commented on app/javascript/composables/giveTagsColor.ts
> +export default function giveTagsColor(tags : Tag[]) {
al final le asigna un color aleatorio a cada tag :) randomItem va sacando los colores, así que no se debería repetir ninguno a menos que se acaben los colores y ahí corre el método resetColors. el tema era que cada tag necesitaba un color distinto y como lo uso en dos vistas se hacía más fácil llevarlo a un composable. por mi parte creo que lo más simple para evitar todo eso (y el tagColor y todos esos cambios) sería agregar un color aleatorio como atributo del modelo, pero ahí entra la discusión de si es una separación adecuada de front y back

2023-01-03 20:42 UTC, riadeane commented on spec/requests/api/internal/feedback_sessions_spec.rb
> +      it { expect(created_session['tags'].count).to eq(1) }
bueena! lo agrego

2023-01-03 20:43 UTC, riadeane commented on app/javascript/components/base-tag.vue
> +  tag: TagColor;
sii, era para simplificarlo en los componentes que usan este para que solo les pase un prop "tag" y listo, todo el tema del tagColor es meramente visual

2023-01-03 20:44 UTC, riadeane commented on app/javascript/components/base-tag.vue
> +  button: boolean;
queda harto más claro así :D voy con ese cambio

2023-01-03 20:45 UTC, riadeane commented on app/javascript/components/base-tag.vue
> +interface StringDictionary {
sii totalmente de acuerdo jajaj se me fue cambiarle el nombre, antes era más simple la interfaz :nerd_face:

2023-01-03 20:45 UTC, riadeane commented on app/javascript/components/base-tag.vue
> +    :class="[tagClasses[props.tag.color].normal, props.button ? tagClasses[props.tag.color].hover : '']"
también de acuerdo :D

2023-01-03 20:49 UTC, riadeane commented on app/javascript/components/feedback-sessions-item.vue
> +  tags: Tag[],
lo pensé para después hacer el filtro y que estén tags iguales pero de distintos items con los mismos colores, me pasó que si hacía lo de giveTagsColors en cada item se le asignaban colores distintos a cada tag y no tenía mucha lógica cuando los ves todos juntos, podías tener el tag "Rails" en azul en un item y luego en rojo en otro. preferí asignarle a cada tag un solo color de una y que después cada item filtrara cuales necesitaba

2023-01-04 12:56 UTC, flouMicaza commented on app/javascript/components/base-tag.vue
> +  tag: TagColor;
Cómo meramente visual? 🤔

2023-01-04 13:06 UTC, flouMicaza commented on app/javascript/composables/giveTagsColor.ts
> +export default function giveTagsColor(tags : Tag[]) {
Yaaa capto capto. Ahora leí el pitch y caché que no dice nada de los colores así que like al approach. 

En otra ocasión si los tags tienen más protagonismo quizás si guardaría en la db los colores, porque al ver los tags de distinto color todas las veces, el color no está aportando mucho a la plataforma y derrepente es mejor ni tenerlo. 

Por ejemplo: si entro a ver mis feedback y veo que rails es amarillo, y después entro denuevo a verlos y ahora rails está azul, no voy a poder usar el color para reconocer más fácil las sesiones de rails (que sería el objetivo de poner colores). 

Pero para este caso encuentro que está perfect como lo hiciste 👯

2023-01-04 13:10 UTC, flouMicaza commented on app/javascript/components/feedback-sessions-item.vue
> +  tags: Tag[],
yaa super. 
Creo que hay una forma de crear variables "globales" en vue. Como que la asignas al montar la primera vista y es accesible desde todos los hijos, así se ahorra esto de mandar los tags como props, que en verdad no es info específica del componente sino que algo global. 
No me acuerdo como que se llama pero voy a preguntar en techi banana y etiqutarte jajajaaj 
Lo dejo como comentario solo para que sepas que existe 😄

2023-01-04 13:17 UTC, flouMicaza commented on app/javascript/components/feedback-sessions-item.vue
> +  tags: Tag[],
https://platanus.slack.com/archives/C01CEGVK0AY/p1672837762101459 jeje

2023-01-04 14:43 UTC, riadeane commented on app/javascript/components/base-tag.vue
> +  tag: TagColor;
que solo incluye el color asignado, no cambia mucho sobre lo que representa tag en sí

2023-01-04 14:44 UTC, flouMicaza commented on app/javascript/components/base-tag.vue
> +  tag: TagColor;
ahhhhh ya cache! Entonces quizás debería llamarse TagWithColor :O

2023-01-04 14:44 UTC, riadeane commented on app/javascript/composables/giveTagsColor.ts
> +export default function giveTagsColor(tags : Tag[]) {
Sii, también creo lo mismo. Para la próxima es harto más simple solamente asignar los colores desde antes.

2023-01-04 14:45 UTC, riadeane commented on app/javascript/components/feedback-sessions-item.vue
> +  tags: Tag[],
Uuu lo voy a implementar :smile: Así también pueden tener todos el mismo color!!

2023-01-04 14:46 UTC, flouMicaza commented on app/javascript/components/feedback-sessions-item.vue
> +  tags: Tag[],
Si quieres quizás puedes dejar este pr como está y luego hacer otro pr para arreglar eso. Si no quieres que quede demaciado lleno de comentarios y commits

2023-01-04 17:32 UTC, riadeane commented on app/javascript/components/feedback-sessions-item.vue
> +  tags: Tag[],
Lo llevo intentando y no me funciona :( No estoy cachando bien qué retorna, porque al hacer inject parece que no me está dando un array

2023-01-04 17:39 UTC, monkeyci commented on lib/fake_data_loader.rb
> +    tags = %w[Backend Frontend UX/UI Vue Rails Tailwind TypeScript ActiveAdmin RSpec CircleCI Modelos]
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/LineLength: Line is too long. [102/100]

2023-01-04 17:39 UTC, monkeyci commented on spec/requests/api/internal/feedback_sessions_spec.rb
> +
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/EmptyLines: Extra blank line detected.

2023-01-04 18:05 UTC, ldlsegovia approved these changes
👏🏻

2023-01-04 19:42 UTC, flouMicaza commented on app/javascript/components/feedback-sessions-item.vue
> +  tags: Tag[],
puchaa :( yo creo que en techi banana demás que alguien ya lo ha usado y cacha bien cómo usarlo, o podemos agendar un pair programming mañana en la tarde si quieres y decifrarlo 👯  Peeeero quizás para otra funcionalidad lo puedes tener en mente para probarlo y ahora avanzas a otro pitch nomás, si igual cómo lo implementaste yo creo que está bacan.
Yyyy pasa harto en proyectos con clientes que quieren salir rápido y la solución que unx pensó al inicio tiene que quedar nomás y después en tiempos de refactor se puede mejorar 😸

2023-01-04 19:42 UTC, flouMicaza approved these changes
💯

2023-01-04 20:30 UTC, riadeane commented on app/javascript/components/feedback-sessions-item.vue
> +  tags: Tag[],
vuelvo el miércoles!! pero feliz de juntarnos para verlo, quedé con la duda de cómo funciona jiji y sí o sí quiero hacer algo de mejora continua aquí :D

2023-01-04 20:30 UTC, merged