Agregar vistas de ActiveAdmin
platanus/fdbk1 pull request #4
Opened 2023-01-03 18:58 UTC by riadeane

### Contexto
Holii vengo con la última PR :tada: Voy a hacer copy paste de mi ultimo contexto
Uno de los proyectos de sandbox de los trainees es trabajar en una [aplicación de feedback técnico](https://www.notion.so/platanus/Aplicaci-n-de-feedback-t-cnico-6fbf380eec134f0292bd1c0ebd224af8). Dentro de este proyecto a mí me corresponde realizar el pitch [Tags + Creación de sesiones de feedback](https://www.notion.so/platanus/Tags-Creaci-n-de-sesiones-83964f537b3d4d67ba1e02e0d0aff351). Pueden comparar las vistas con el [Figma](https://www.figma.com/file/8qvUPFU10bXqVbhALa0aQc/Proyecto-Trainee---FDBK?t=9nKpcS4Zxc4mdDMH-0)
​
### Qué se esta haciendo
​Aquí se agregan las vistas de ActiveAdmin para las FeedbackSessions, Tags y SessionTags
#### En particular hay que revisar
Según yo nada en particular, es bien cortita esta PR y tiene lo típico de ActiveAdmin
​

-----------
#### Info Adicional (pantallazos, links, fuentes, etc.)
Si necesitan pantallazo me avisan, pero no creo que sea necesario

2023-01-03 20:41 UTC, difernandez requested changes

2023-01-03 20:41 UTC, difernandez commented on app/admin/feedback_sessions.rb
> +  permit_params :email, :password, :password_confirmation
esto se debe haber pasado de copy paste del admin de user jeje debería permitir las cosas que hay en el form

2023-01-03 20:41 UTC, difernandez commented on app/admin/tags.rb
> +  permit_params :email, :password, :password_confirmation
idem permitir lo del form

2023-01-03 20:41 UTC, difernandez commented on app/admin/session_tags.rb
> +  permit_params :email, :password, :password_confirmation
idem permitir lo del form

2023-01-03 20:41 UTC, difernandez commented on app/admin/tags.rb
> +      f.input :session_tags
puede que pasen cosas raras teniendo ambos o no? Onda el `has_many` y el `has_many :through`. Como que podría poner algunas sesiones por un lado y otras por el otro. Creo que me haría sentido incluir solo las feedback sessions, cosa que sea como un multiselect y poder asociarle feedback sessions ahí no más, o derechamente no poner las sesiones en este form y que se agreguen solo a través del admin de la sesión, ahí con un multiselect. Qué opinas?

2023-01-03 20:44 UTC, nicolasguridi approved these changes
Lo veo bien! 💯 Ojo con el comentario de diego de los params nomás

2023-01-03 20:44 UTC, nicolasguridi commented on app/admin/feedback_sessions.rb
> +  end
Esto está bien, pero por si te sirve para más adelante: me parece que Active Admin agrega filtros y forms por defecto que cubren todo lo más estándar, así no hay que agregarlos a mano todas las veces. Cuando quieres algo más custom estás obligada a agregarlos tú

2023-01-04 19:05 UTC, riadeane commented on app/admin/tags.rb
> +      f.input :session_tags
Sii totalmente de acuerdo, al final las session_tags se generan de forma automática. Lo voy a dejar con solo los feedback_sessions

2023-01-04 19:18 UTC, difernandez approved these changes
🚀

2023-01-04 19:18 UTC, merged